med_first:
    resource: "@MedFirstBundle/Resources/config/routing.yml"
    prefix:   /med

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /dashboard
    type: annotation